Withdraws\Settings\Code\Tables\Settings:
  table: withdraws_settings
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    user_id:
      name: user_id
      type: integer
      length: 11
      nullable: false
    id_passport:
      name: id_passport
      type: string
      length: 255
      nullable: true
    pin:
      name: pin
      type: string
      length: 255
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: true
    date_created:
      name: date_created
      type: datetime
      nullable: true
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: true
    date_modified:
      name: date_modified
      type: datetime
      nullable: true
  indexes:
    user_id_index:
      columns: [user_id]
    created_by_index:
      columns: [created_by]
    modified_by_index:
      columns: [modified_by]
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
